version: '3'

services:
  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - frontend-pnpm-store:/root/.pnpm-store
      - frontend-node-modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: pnpm dev
    working_dir: /app

volumes:
  frontend-pnpm-store:
  frontend-node-modules: